---
title: "Behavioral Health Research in Primary Care"
author: "<br /> Jake Hedges, LMHC CPS <br /> Ivan Castro, MSPH <br />  <br />  VISN2 Center for Integrated Healthcare"
output:
  xaringan::moon_reader:
    css: ["shinobi-mod.css", "default"]
    lib_dir: libs
    countIncrementalSlides: false
---

## What is the Center for Integrated Healthcare?  

--

__Mission__  

>To improve the healthcare of Veterans by integrating mental health prevention and treatment services into the primary care setting.  

__Vision__  

>To be a national resource regarding the integration of mental health in primary care.  

---

### Two cores of CIH  

__Education and Implementation Services__   

- Train providers of integrated primary care nationally and advise on best practices.  

- Promote implementation of evidence-based primary care mental health services.  

--

__Research__  

- Focuses on discovering more effective and efficient ways to identify and treat mental health concerns in primary care.  

  - Brief assessment and intervention  
  
- High priority areas include: substance use, PTSD, depression, sleep distrubances

---

class: title-slide

# Primary Care Mental Health Integration (PCMHI)

---

## Why PCMHI? 

- Improves Identification  

  - Identification of depression, psychiatric co-morbidities, and substance misuse _in primary care_.  
  
- Improves Access  

  - Reduces wait time for mental health services  
  - Reduces no-show rates  
  
- Engagement in Care  

  - Same-day services in PCMHI increase the odds of attending future mental health appointments and engaging in specialty treatment (OMH, PCT, STS).  
  
--

__Examples of PCMHI interventions__  

- Brief Cognitive Behavioral Therapy (CBT) for Chronic Pain  
- Tobacco Use Cessation: A Brief Primary Care Intervention  
- Prolonged Exposure for Primary Care (PE-PC)  
- Brief CBT for Insomnia  

---

class: title-slide 

# Conducting research within Primary Care 
---

## Clinical Research  

- Safety assessments  

  - Blessed Orientation-Memory-Concentration Test  
  - P4 Suicide Screener  
  - Breathalyzer  
  
- Diagnostic assessments  
  
  - Clinician Administered PTSD Scale  

- Self-report assessments  

  - PTSD Checklist for DSM-5  
  - Alcohol Use Disorders Identification Test  
  - Patient Health Questionnaire  
  - Substance Use Motives Questionnaire  

---

## Recruitment  

- Patients are recruited from VA primary care clinics  
  - recruitment letter and phone screens  

- In-person interviews at baseline  
  - those eligible for a study are randomized to experimental treatment or treatment-as-usual.  
  
- Inclusion criteria  
  - diagnostic level (or subthreshold) PTSD  
    - PCL-5 >= 30  
  - hazardous alcohol use  
    - AUDIT 6-25 (women) or 8-25 (men)  
  
- Exclusion criteria  
  - gross cognitive impairment  
  - recent suicidal intent or attempt  
  - current psychotherapy for PTSD  
  - medication  
    - changes in last 2 months for PTSD  
    - or current prescription for substance use (alcohol studies)  
  - desire to begin specialty care  

---

## Some studies we're involved with

- Clinician-supported PTSD Coach  
  - study incorporates use of a mobile app and focuses on increasing patient's ability to manage symptoms, and preparing them for further treatment if needed.  
  
- Primary Care Brief Mindfulness Training  
  - mindfulness training is not psychotherapy, but these classes are meant to help veterans increase emotional regulation skills.  
  
- Primary Care Treatment Integrating Motivation and Exposure  
  - study focuses on decreasing alcohol use _and_ PTSD symptoms by integrating PE-PC and motivational interviewing for alcohol use.  
  
- Peer-Delivered Whole Health Coaching  
  - intervention is _not_ focused on PTSD symptoms, and is ideal for Veterans with PTSD who are reluctant to talk about behavioral problems.  
  
---

## Challenges to Recruitment and Engagement

- Reluctance to talk about trauma  

- Stigma/Motivation to change   

- Perceptions  
  - *Don't waste resources on me*  
  - *This should go to someone who really needs it*   

- Assessments can be exhausting and frustrating  
 
- Studies may require 'homework', or use of tools at home  

---

## Challenges continued

- Meeting criteria for PTSD and severity cut-off

- Scheduling conflict, not enought time to devote to study

- *I don't have a drinking problem*, or denying PTSD symptoms


---

## How We Address Challenges

- Motivational interviewing

- Explaining that participation may help other veterans

- Rewording/rephrasing interventions in order to reduce stigma, i.e. mindfulness class, avoiding framing drinking as *drinking to cope*
  
- Clarify as much as possible, keep veteran connected with the bigger picture of the study

---

## Resources  

- [Center for Integrated Healthcare](https://www.mirecc.va.gov/cih-visn2/)  

- [Primary Care - Mental Health Integration](https://www.patientcare.va.gov/primarycare/PCMHI.asp)  

- [Other Integrated Care Links](https://www.mirecc.va.gov/cih-visn2/other_integrated_care_links.asp)  




